# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='New', verbose_name='News title')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('author', models.TextField(default='Author', verbose_name='Newws Author')),
                ('body', models.TextField(default='Body', verbose_name='News body')),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
