# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180419_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=b'New', verbose_name=b'Papers title')),
                ('foto_title', models.TextField(default=b'New', verbose_name=b'Foto title')),
                ('author', models.TextField(default=b'Author', verbose_name=b'Papers Author')),
                ('body', models.TextField(default=b'Body', verbose_name=b'Papers body')),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['posted'],
            },
        ),
    ]
