# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.TextField(default=b'', verbose_name=b'Adres of object')),
                ('name', models.TextField(default=b'', verbose_name=b'Name of user')),
                ('email', models.TextField(default=b'', verbose_name=b'Email of user')),
                ('object_name', models.TextField(default=b'', verbose_name=b'Object name')),
            ],
            options={
                'ordering': ['adres'],
            },
        ),
    ]
