# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_mapobjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobjects',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mapobjects',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mapobjects',
            name='adres',
            field=models.TextField(default='', verbose_name='Adres of object'),
        ),
        migrations.AlterField(
            model_name='mapobjects',
            name='email',
            field=models.TextField(default='', verbose_name='Email of user'),
        ),
        migrations.AlterField(
            model_name='mapobjects',
            name='name',
            field=models.TextField(default='', verbose_name='Name of user'),
        ),
        migrations.AlterField(
            model_name='mapobjects',
            name='object_name',
            field=models.TextField(default='', verbose_name='Object name'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='author',
            field=models.TextField(default='Author', verbose_name='Papers Author'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='body',
            field=models.TextField(default='Body', verbose_name='Papers body'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='foto_title',
            field=models.TextField(default='New', verbose_name='Foto title'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='title',
            field=models.TextField(default='New', verbose_name='Papers title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='author',
            field=models.TextField(default='Author', verbose_name='Service Author'),
        ),
        migrations.AlterField(
            model_name='service',
            name='body',
            field=models.TextField(default='Body', verbose_name='Service body'),
        ),
        migrations.AlterField(
            model_name='service',
            name='foto',
            field=models.TextField(default='Foto', verbose_name='Way to foto'),
        ),
        migrations.AlterField(
            model_name='service',
            name='foto_title',
            field=models.TextField(default='Foto', verbose_name='Foto title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(default='New', verbose_name='Service title'),
        ),
    ]
