# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20180602_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapobjects',
            old_name='lon',
            new_name='lat',
        ),
    ]
