# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-10 06:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_mapobjects_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapobjects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 6, 36, 43, 174896)),
        ),
    ]
