# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-28 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20181110_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.TextField(default=b'../static/img/news'),
        ),
        migrations.AlterField(
            model_name='mapobjects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 8, 56, 20, 4095)),
        ),
    ]
