# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-28 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20190328_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapobjects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 9, 30, 12, 528358)),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=b'static/img/'),
        ),
    ]
