# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-28 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20190328_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapobjects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 11, 59, 8, 13714)),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=b'media'),
        ),
    ]
