# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-28 12:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20190328_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapobjects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 12, 13, 4, 945138)),
        ),
    ]
