# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-29 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20190328_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ansver',
            field=models.TextField(default=b'', verbose_name=b'Ansver Body'),
        ),
        migrations.AlterField(
            model_name='mapobjects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 6, 4, 52, 534907)),
        ),
    ]
