# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-29 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20190329_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=b'image.jpeg', upload_to=b'media'),
        ),
        migrations.AlterField(
            model_name='mapobjects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 7, 46, 4, 422535)),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=b'image.jpeg', upload_to=b'media'),
        ),
    ]
